#!/usr/bin/bash
#
# Build with ...
# 
#     build -d NN
#
# ... where NN is the day, such as 02 for day 2
#
# Tested with DITA-OT 4.2.3, with the com.arkadianriver.aoc plugin installed
# for the XSL preprocessing, of course.
#

thisdir=`pwd`

case $1 in
	#-i)
	#	pushd plugins
	#	rm *.zip
	#	zip -r com.arkadianriver.aoc.zip com.arkadianriver.aoc/
	#	dita uninstall com.arkadianriver.aoc
	#	dita install com.arkadianriver.aoc.zip
	#	popd
	#	;;
	-d)
		rm -r docs
		dita -i src/aoc-2024.ditamap -f html5 -v -l tmp/out.log -o docs \
		     --html5.toc.generate=no --nav-toc=full --args.output.base=aoc-2024 --args.copycss=yes \
			 --args.cssroot=$thisdir/src --args.css=aoc.css --args.hdf=$thisdir/src/hdf.xml \
			 -Dday=$2
		touch docs/.nojekyll
		;;
	*)	#printf 'usage: build [-i|-d <day>]\nwhere:\n  -i       re-installs an updated plugin\n  -d <day> runs XSL for that day\n'
		printf 'usage: build [-d <day>]\nwhere:\n  -d <day> Runs the XSL template for that day\n'
		;;
esac
